# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0007_auto_20150628_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('trainer', models.BooleanField(default=False)),
                ('average_watts', models.FloatField(default=-1.0)),
                ('private', models.BooleanField(default=False)),
                ('commute', models.BooleanField(default=False)),
                ('average_temp', models.IntegerField(default=-1)),
                ('guid', models.CharField(default=b'', max_length=200)),
                ('start_date_local', models.DateTimeField(default=django.utils.timezone.now)),
                ('average_speed', models.FloatField(default=-1.0)),
                ('start_longitude', models.FloatField(default=-1.0)),
                ('comment_count', models.IntegerField(default=-1)),
                ('type', models.CharField(default=b'', max_length=200)),
                ('photo_count', models.IntegerField(default=-1)),
                ('distance', models.FloatField(default=-1.0)),
                ('average_heartrate', models.FloatField(default=-1.0)),
                ('has_kudoed', models.BooleanField(default=False)),
                ('weighted_average_watts', models.IntegerField(default=-1)),
                ('max_heartrate', models.IntegerField(default=-1)),
                ('name', models.CharField(default=b'', max_length=200)),
                ('manual', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('flagged', models.BooleanField(default=False)),
                ('average_cadence', models.FloatField(default=-1.0)),
                ('athlete_count', models.IntegerField(default=-1)),
                ('truncated', models.IntegerField(default=-1)),
                ('workout_type', models.CharField(default=b'', max_length=200)),
                ('device_watts', models.BooleanField(default=False)),
                ('location_city', models.CharField(default=b'', max_length=200)),
                ('location_country', models.CharField(default=b'', max_length=200)),
                ('elapsed_time', models.IntegerField(default=-1)),
                ('kudos_count', models.IntegerField(default=-1)),
                ('kilojoules', models.FloatField(default=-1.0)),
                ('description', models.CharField(default=b'', max_length=200)),
                ('moving_time', models.IntegerField(default=-1)),
                ('max_speed', models.FloatField(default=-1.0)),
                ('gear_id', models.CharField(default=b'', max_length=200)),
                ('location_state', models.CharField(default=b'', max_length=200)),
                ('total_elevation_gain', models.FloatField(default=-1.0)),
                ('calories', models.FloatField(default=-1.0)),
                ('start_latitude', models.FloatField(default=-1.0)),
                ('upload_id', models.CharField(default=b'', max_length=200)),
                ('achievement_count', models.IntegerField(default=-1)),
                ('external_id', models.CharField(default=b'', max_length=200)),
                ('instagram_primary_photo', models.CharField(default=b'', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('activity_id', models.IntegerField(default=-1)),
                ('text', models.CharField(default=b'', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityKudos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('profile', models.CharField(default=b'', max_length=200)),
                ('premium', models.BooleanField(default=False)),
                ('firstname', models.CharField(default=b'', max_length=200)),
                ('lastname', models.CharField(default=b'', max_length=200)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sex', models.CharField(default=b'', max_length=200)),
                ('follower', models.CharField(default=b'', max_length=200)),
                ('profile_medium', models.CharField(default=b'', max_length=200)),
                ('city', models.CharField(default=b'', max_length=200)),
                ('country', models.CharField(default=b'', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approve_followers', models.BooleanField(default=False)),
                ('state', models.CharField(default=b'', max_length=200)),
                ('friend', models.CharField(default=b'', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLap',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('start_date_local', models.DateTimeField(default=django.utils.timezone.now)),
                ('moving_time', models.IntegerField(default=-1)),
                ('average_heartrate', models.FloatField(default=-1.0)),
                ('device_watts', models.BooleanField(default=False)),
                ('max_heartrate', models.FloatField(default=-1.0)),
                ('start_index', models.IntegerField(default=-1)),
                ('distance', models.FloatField(default=-1.0)),
                ('name', models.CharField(default=b'', max_length=200)),
                ('total_elevation_gain', models.FloatField(default=-1.0)),
                ('average_speed', models.FloatField(default=-1.0)),
                ('end_index', models.IntegerField(default=-1)),
                ('elapsed_time', models.IntegerField(default=-1)),
                ('max_speed', models.FloatField(default=-1.0)),
                ('average_cadence', models.FloatField(default=-1.0)),
                ('lap_index', models.IntegerField(default=-1)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('average_watts', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPhoto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', models.CharField(default=b'', max_length=200)),
                ('ref', models.CharField(default=b'', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity_id', models.IntegerField(default=-1)),
                ('caption', models.CharField(default=b'', max_length=200)),
                ('type', models.CharField(default=b'', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BaseActivityZone',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type', models.CharField(default=b'', max_length=200)),
                ('sensor_based', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BaseEffort',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('kom_rank', models.IntegerField(default=-1)),
                ('start_date_local', models.DateTimeField(default=django.utils.timezone.now)),
                ('moving_time', models.IntegerField(default=-1)),
                ('average_heartrate', models.FloatField(default=-1.0)),
                ('pr_rank', models.IntegerField(default=-1)),
                ('start_index', models.IntegerField(default=-1)),
                ('distance', models.IntegerField(default=-1)),
                ('name', models.CharField(default=b'', max_length=200)),
                ('max_heartrate', models.FloatField(default=-1.0)),
                ('end_index', models.IntegerField(default=-1)),
                ('elapsed_time', models.IntegerField(default=-1)),
                ('average_watts', models.FloatField(default=-1.0)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('average_cadence', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='BestEffort',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('profile', models.CharField(default=b'', max_length=200)),
                ('profile_medium', models.CharField(default=b'', max_length=200)),
                ('name', models.CharField(default=b'', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HeartrateActivityZone',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('points', models.IntegerField(default=-1)),
                ('custom_zones', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=-1)),
                ('max', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='LoadableEntity',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaceActivityZone',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('sample_race_distance', models.IntegerField(default=-1)),
                ('score', models.IntegerField(default=-1)),
                ('sample_race_time', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='PowerActivityZone',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('athlete_weight', models.FloatField(default=-1.0)),
                ('bike_weight', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('athlete_count', models.IntegerField(default=-1)),
                ('end_longitude', models.FloatField(default=-1.0)),
                ('distance', models.FloatField(default=-1.0)),
                ('hazardous', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('private', models.BooleanField(default=False)),
                ('elevation_low', models.FloatField(default=-1.0)),
                ('end_latitude', models.FloatField(default=-1.0)),
                ('starred', models.BooleanField(default=False)),
                ('city', models.CharField(default=b'', max_length=200)),
                ('climb_category', models.IntegerField(default=-1)),
                ('name', models.CharField(default=b'', max_length=200)),
                ('total_elevation_gain', models.FloatField(default=-1.0)),
                ('country', models.CharField(default=b'', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(default=b'', max_length=200)),
                ('star_count', models.IntegerField(default=-1)),
                ('start_latitude', models.FloatField(default=-1.0)),
                ('start_longitude', models.FloatField(default=-1.0)),
                ('elevation_high', models.FloatField(default=-1.0)),
                ('maximum_grade', models.FloatField(default=-1.0)),
                ('average_grade', models.FloatField(default=-1.0)),
                ('effort_count', models.IntegerField(default=-1)),
                ('activity_type', models.CharField(default=b'', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentEffort',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentExplorerResult',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('distance', models.FloatField(default=-1.0)),
                ('climb_category', models.IntegerField(default=-1)),
                ('name', models.CharField(default=b'', max_length=200)),
                ('elev_difference', models.FloatField(default=-1.0)),
                ('avg_grade', models.FloatField(default=-1.0)),
                ('climb_category_desc', models.CharField(default=b'', max_length=200)),
                ('SegmentExplorerResult_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('resolution', models.CharField(default=b'', max_length=200)),
                ('original_size', models.IntegerField(default=-1)),
                ('series_type', models.CharField(default=b'', max_length=200)),
                ('type', models.CharField(default=b'', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Rando',
        ),
        migrations.AddField(
            model_name='athlete',
            name='badge_type_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='dateofbirth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
