# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0008_auto_20150629_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='achievement_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='athlete_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='average_cadence',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='average_heartrate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='average_speed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='average_temp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='average_watts',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='calories',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='comment_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='commute',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='device_watts',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='elapsed_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='external_id',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='flagged',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='gear_id',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='guid',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='has_kudoed',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='instagram_primary_photo',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='kilojoules',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='kudos_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location_city',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location_country',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location_state',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='manual',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_heartrate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_speed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='moving_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='photo_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='private',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date_local',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='total_elevation_gain',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='trainer',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='truncated',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='upload_id',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='weighted_average_watts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='workout_type',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activitycomment',
            name='activity_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activitycomment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='activitycomment',
            name='text',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activitykudos',
            name='approve_followers',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='activitykudos',
            name='city',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activitykudos',
            name='country',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activitykudos',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='activitykudos',
            name='firstname',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activitykudos',
            name='follower',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activitykudos',
            name='friend',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activitykudos',
            name='lastname',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activitykudos',
            name='premium',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='activitykudos',
            name='profile',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activitykudos',
            name='profile_medium',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activitykudos',
            name='sex',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activitykudos',
            name='state',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activitykudos',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='activitylap',
            name='average_cadence',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activitylap',
            name='average_heartrate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activitylap',
            name='average_speed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activitylap',
            name='average_watts',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activitylap',
            name='device_watts',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='activitylap',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activitylap',
            name='elapsed_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activitylap',
            name='end_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activitylap',
            name='lap_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activitylap',
            name='max_heartrate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activitylap',
            name='max_speed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activitylap',
            name='moving_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activitylap',
            name='name',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activitylap',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='activitylap',
            name='start_date_local',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='activitylap',
            name='start_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activitylap',
            name='total_elevation_gain',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activityphoto',
            name='activity_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activityphoto',
            name='caption',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activityphoto',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='activityphoto',
            name='ref',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activityphoto',
            name='type',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activityphoto',
            name='uid',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activityphoto',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='agreed_to_terms',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='approve_followers',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='badge_type_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='biggest_climb_elevation_gain',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='biggest_ride_distance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='city',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='country',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='date_preference',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='dateofbirth',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='description',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='email',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='email_facebook_twitter_friend_joins',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='email_kom_lost',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='email_language',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='email_send_follower_notices',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='facebook_sharing_enabled',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='firstname',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='follower',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='follower_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='follower_request_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='friend',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='friend_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='ftp',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='global_privacy',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='instagram_username',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='lastname',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='max_heartrate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='measurement_preference',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='mutual_friend_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='offer_in_app_payment',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='plan',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='premium',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='premium_expiration_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='profile',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='profile_medium',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='profile_original',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='receive_comment_emails',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='receive_follower_feed_emails',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='receive_kudos_emails',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='receive_newsletter',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sample_race_distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sample_race_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sex',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='state',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='super_user',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='username',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='baseactivityzone',
            name='sensor_based',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='baseactivityzone',
            name='type',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='baseeffort',
            name='average_cadence',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='baseeffort',
            name='average_heartrate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='baseeffort',
            name='average_watts',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='baseeffort',
            name='distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='baseeffort',
            name='elapsed_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='baseeffort',
            name='end_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='baseeffort',
            name='kom_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='baseeffort',
            name='max_heartrate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='baseeffort',
            name='moving_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='baseeffort',
            name='name',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='baseeffort',
            name='pr_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='baseeffort',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='baseeffort',
            name='start_date_local',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='baseeffort',
            name='start_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='profile',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='profile_medium',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='heartrateactivityzone',
            name='custom_zones',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='heartrateactivityzone',
            name='max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heartrateactivityzone',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heartrateactivityzone',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paceactivityzone',
            name='sample_race_distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paceactivityzone',
            name='sample_race_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paceactivityzone',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='poweractivityzone',
            name='athlete_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='poweractivityzone',
            name='bike_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='activity_type',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='athlete_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='average_grade',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='city',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='climb_category',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='country',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='effort_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='elevation_high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='elevation_low',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='end_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='end_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='hazardous',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='segment',
            name='maximum_grade',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='name',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='private',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='segment',
            name='star_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='starred',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='segment',
            name='start_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='start_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='state',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='total_elevation_gain',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='segmenteffort',
            name='hidden',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='segmentexplorerresult',
            name='SegmentExplorerResult_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='segmentexplorerresult',
            name='avg_grade',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='segmentexplorerresult',
            name='climb_category',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='segmentexplorerresult',
            name='climb_category_desc',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='segmentexplorerresult',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='segmentexplorerresult',
            name='elev_difference',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='segmentexplorerresult',
            name='name',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='original_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='resolution',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='series_type',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='type',
            field=models.CharField(default=b'', max_length=200, null=True),
        ),
    ]
