# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0009_auto_20150629_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='athlete_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='best_efforts_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='map_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='photos_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='segment_efforts_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='splits_metric_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='splits_standard_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activitycomment',
            name='athlete_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activitylap',
            name='activity_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activitylap',
            name='athlete_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='all_ride_totals_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='all_run_totals_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='bikes_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='clubs_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='recent_ride_totals_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='recent_run_totals_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='shoes_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='ytd_ride_totals_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='ytd_run_totals_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseactivityzone',
            name='distribution_buckets_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseeffort',
            name='achievements_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseeffort',
            name='activity_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseeffort',
            name='athlete_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseeffort',
            name='segment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='map_id',
            field=models.IntegerField(null=True),
        ),
    ]
